### ISSUE TITLE
streamer bug

### ISSUE THREAD

**Issue by mitjacotic** [PopcornTimeCE/popcorntimece#1]
There is a bug which was fixed in a butter project, setting the episode and season should be swapped in this line and the line below:
https://github.com/PopcornTimeCE/popcorntimece/blob/master/src/app/lib/streamer.js#L403

**Comment by DiscoveryOV** [comment]
So are you saying it should be:

    model.set('season', sub_data.episode);
    model.set('episode', sub_data.season);
and not
    model.set('episode', sub_data.season);
    model.set('season', sub_data.episode);
?
or
    model.set('season', sub_data.season);
    model.set('episode', sub_data.episode);
?

Thanks

**Comment by DiscoveryOV** [comment]
Nevermind figured it out. Thanks for the tip :)
